<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoalQuisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $soalBeginner = [
            //a groups
            [
                'huruf_id' => 'H-GO-A',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'あ',
                'correct_answer' => 'a',
                'option_a' => 'a',
                'option_b' => 'i',
                'option_c' => 'u',
                'option_d' => 'e',
            ],
            [
                'huruf_id' => 'H-GO-I',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'い',
                'correct_answer' => 'b',
                'option_a' => 'e',
                'option_b' => 'i',
                'option_c' => 'o',
                'option_d' => 'a',
            ],
            [
                'huruf_id' => 'H-GO-U',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'う',
                'correct_answer' => 'a',
                'option_a' => 'u',
                'option_b' => 'o',
                'option_c' => 'i',
                'option_d' => 'a',
            ],
            [
                'huruf_id' => 'H-GO-E',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'え',
                'correct_answer' => 'b',
                'option_a' => 'i',
                'option_b' => 'e',
                'option_c' => 'u',
                'option_d' => 'o',
            ],
            [
                'huruf_id' => 'H-GO-O',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'お',
                'correct_answer' => 'c',
                'option_a' => 'e',
                'option_b' => 'a',
                'option_c' => 'o',
                'option_d' => 'i',
            ],
            //end a groups
            //ta groups
            [
                'huruf_id' => 'H-GO-TA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'た',
                'correct_answer' => 'a',
                'option_a' => 'ta',
                'option_b' => 'na',
                'option_c' => 'ka',
                'option_d' => 'shi',
            ],
            [
                'huruf_id' => 'H-GO-CHI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ち',
                'correct_answer' => 'c',
                'option_a' => 'tsu',
                'option_b' => 'te',
                'option_c' => 'chi',
                'option_d' => 'ko',
            ],
            [
                'huruf_id' => 'H-GO-TSU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'つ',
                'correct_answer' => 'b',
                'option_a' => 'chi',
                'option_b' => 'tsu',
                'option_c' => 'to',
                'option_d' => 'ku',
            ],
            [
                'huruf_id' => 'H-GO-TE',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'て',
                'correct_answer' => 'd',
                'option_a' => 'se',
                'option_b' => 'da',
                'option_c' => 'chi',
                'option_d' => 'te',
            ],
            [
                'huruf_id' => 'H-GO-TO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'と',
                'correct_answer' => 'a',
                'option_a' => 'to',
                'option_b' => 'na',
                'option_c' => 'su',
                'option_d' => 'de',
            ],
            //end ta groups

            //ma groups
            [
                'huruf_id' => 'H-GO-MA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ま',
                'correct_answer' => 'c',
                'option_a' => 'na',
                'option_b' => 'mu',
                'option_c' => 'ma',
                'option_d' => 'ra',
            ],
            [
                'huruf_id' => 'H-GO-MI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'み',
                'correct_answer' => 'd',
                'option_a' => 'ni',
                'option_b' => 'me',
                'option_c' => 'mo',
                'option_d' => 'mi',
            ],
            [
                'huruf_id' => 'H-GO-MU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'む',
                'correct_answer' => 'a',
                'option_a' => 'mu',
                'option_b' => 'mo',
                'option_c' => 'bu',
                'option_d' => 'tsu',
            ],
            [
                'huruf_id' => 'H-GO-ME',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'め',
                'correct_answer' => 'b',
                'option_a' => 're',
                'option_b' => 'me',
                'option_c' => 'ne',
                'option_d' => 'mi',
            ],
            [
                'huruf_id' => 'H-GO-MO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'も',
                'correct_answer' => 'd',
                'option_a' => 'ho',
                'option_b' => 'ma',
                'option_c' => 'no',
                'option_d' => 'mo',
            ],
            //end ma groups

            //n groups
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Apa pelafalan yang tepat untuk karakter berikut?',
                'character' => 'ん',
                'correct_answer' => 'b',
                'option_a' => 'na',
                'option_b' => 'n',
                'option_c' => 'ne',
                'option_d' => 'mu',
            ],

        ];

        $soalIntermediate = [
            //a groups
            [
                'huruf_id' => 'H-GO-A',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'あする',
                'correct_answer' => 'c',
                'option_a' => 'aruhi',
                'option_b' => 'akuto',
                'option_c' => 'asuru',
                'option_d' => 'amami',
            ],
            [
                'huruf_id' => 'H-GO-I',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'いけんや',
                'correct_answer' => 'a',
                'option_a' => 'ikenya',
                'option_b' => 'ikuto',
                'option_c' => 'isura',
                'option_d' => 'imami',
            ],
            [
                'huruf_id' => 'H-GO-U',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'うみた',
                'correct_answer' => 'b',
                'option_a' => 'umisa',
                'option_b' => 'umita',
                'option_c' => 'usuta',
                'option_d' => 'umata',
            ],
            [
                'huruf_id' => 'H-GO-E',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'えのつ',
                'correct_answer' => 'd',
                'option_a' => 'enasa',
                'option_b' => 'ekuto',
                'option_c' => 'esura',
                'option_d' => 'enotsu',
            ],
            [
                'huruf_id' => 'H-GO-O',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'おろみ',
                'correct_answer' => 'a',
                'option_a' => 'oromi',
                'option_b' => 'okuta',
                'option_c' => 'osura',
                'option_d' => 'omami',
            ],
            //end a groups
            //ta groups
            [
                'huruf_id' => 'H-GO-TA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'たちつ',
                'correct_answer' => 'c',
                'option_a' => 'tato',
                'option_b' => 'tachi',
                'option_c' => 'tachitsu',
                'option_d' => 'tetsu',
            ],
            [
                'huruf_id' => 'H-GO-CHI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ちてと',
                'correct_answer' => 'a',
                'option_a' => 'chiteto',
                'option_b' => 'chitto',
                'option_c' => 'cheto',
                'option_d' => 'chite',
            ],
            [
                'huruf_id' => 'H-GO-TSU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'つたち',
                'correct_answer' => 'b',
                'option_a' => 'tsuchi',
                'option_b' => 'tsutachi',
                'option_c' => 'tsuto',
                'option_d' => 'tsuchi',
            ],
            [
                'huruf_id' => 'H-GO-TE',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'てとち',
                'correct_answer' => 'd',
                'option_a' => 'teto',
                'option_b' => 'tetechi',
                'option_c' => 'toti',
                'option_d' => 'tetochi',
            ],
            [
                'huruf_id' => 'H-GO-TO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'とつて',
                'correct_answer' => 'b',
                'option_a' => 'totutsute',
                'option_b' => 'totsute',
                'option_c' => 'totute',
                'option_d' => 'totsute',
            ],
            //end ta groups
            //ma groups
            [
                'huruf_id' => 'H-GO-MA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'まみも',
                'correct_answer' => 'b',
                'option_a' => 'mamumo',
                'option_b' => 'mamimo',
                'option_c' => 'mameme',
                'option_d' => 'mamomi',
            ],
            [
                'huruf_id' => 'H-GO-MI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'みむま',
                'correct_answer' => 'd',
                'option_a' => 'mumami',
                'option_b' => 'mamimu',
                'option_c' => 'mimamo',
                'option_d' => 'mimuma',
            ],
            [
                'huruf_id' => 'H-GO-MU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'むめもま',
                'correct_answer' => 'a',
                'option_a' => 'mumemoma',
                'option_b' => 'mumamemo',
                'option_c' => 'mumemama',
                'option_d' => 'mumememi',
            ],
            [
                'huruf_id' => 'H-GO-ME',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'めまみ',
                'correct_answer' => 'c',
                'option_a' => 'memimi',
                'option_b' => 'mamemi',
                'option_c' => 'memami',
                'option_d' => 'mimema',
            ],
            [
                'huruf_id' => 'H-GO-MO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'もまむめ',
                'correct_answer' => 'a',
                'option_a' => 'momamume',
                'option_b' => 'momemamu',
                'option_c' => 'momimemu',
                'option_d' => 'momimuma',
            ],
            //end ma groups
            //n groups
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'つん',
                'correct_answer' => 'd',
                'option_a' => 'tsume',
                'option_b' => 'tsumu',
                'option_c' => 'tsuma',
                'option_d' => 'tsun',
            ],
            //end n groups          
        ];

        $soalAdvanced = [
            //a groups
            [
                'huruf_id' => 'H-GO-A',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'あばたがさ',
                'correct_answer' => 'b',
                'option_a' => 'abadasa',
                'option_b' => 'abatagasa',
                'option_c' => 'abatakasa',
                'option_d' => 'abadaso',
            ],
            [
                'huruf_id' => 'H-GO-I',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'いじびぴきぎ',
                'correct_answer' => 'a',
                'option_a' => 'ijibipikigi',
                'option_b' => 'ijibibikiki',
                'option_c' => 'ijibepikigi',
                'option_d' => 'ijibikigiki',
            ],
            [
                'huruf_id' => 'H-GO-U',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'うずづぐぶぷ',
                'correct_answer' => 'c',
                'option_a' => 'uzuzugubupu',
                'option_b' => 'uzudububupu',
                'option_c' => 'uzudugubupu',
                'option_d' => 'uzudugubabu',
            ],
            [
                'huruf_id' => 'H-GO-E',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'えげでぺぜべれ',
                'correct_answer' => 'd',
                'option_a' => 'egedepezepe',
                'option_b' => 'egedezebera',
                'option_c' => 'egedepereze',
                'option_d' => 'egedepezebere',
            ],
            [
                'huruf_id' => 'H-GO-O',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'おどごぼぽそ',
                'correct_answer' => 'a',
                'option_a' => 'odogoboposo',
                'option_b' => 'odogobobosho',
                'option_c' => 'odoguboposo',
                'option_d' => 'odogeboposo',
            ],
            //end a groups
            //ta groups
            [
                'huruf_id' => 'H-GO-TA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ただがたぱ',
                'correct_answer' => 'b',
                'option_a' => 'tadagapapa',
                'option_b' => 'tadagatapa',
                'option_c' => 'tadagabata',
                'option_d' => 'tagadapata',
            ],
            [
                'huruf_id' => 'H-GO-CHI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ちぢぴきちぎ',
                'correct_answer' => 'a',
                'option_a' => 'chidipikichigi',
                'option_b' => 'chijipikachigi',
                'option_c' => 'chidibikikigi',
                'option_d' => 'chidipikigigi',
            ],
            [
                'huruf_id' => 'H-GO-TSU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'つづぶずぷぐ',
                'correct_answer' => 'd',
                'option_a' => 'tsuzubuzupu',
                'option_b' => 'tsuzububupu',
                'option_c' => 'tsuzugububu',
                'option_d' => 'tsuzubuzupugu',
            ],
            [
                'huruf_id' => 'H-GO-TE',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'てげでぺぜべれ',
                'correct_answer' => 'a',
                'option_a' => 'tegedepezebere',
                'option_b' => 'tegadepezebere',
                'option_c' => 'tegedepezebese',
                'option_d' => 'tegadepezepereru',
            ],
            [
                'huruf_id' => 'H-GO-TO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'とどぼぽごも',
                'correct_answer' => 'c',
                'option_a' => 'todobopogomo',
                'option_b' => 'todopobogomo',
                'option_c' => 'todobopogomo',
                'option_d' => 'todobapogomo',
            ],
            //end ta groups
            //ma groups
            [
                'huruf_id' => 'H-GO-MA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'まばがぱま',
                'correct_answer' => 'd',
                'option_a' => 'mabagapama',
                'option_b' => 'mabagapama',
                'option_c' => 'mabakapapa',
                'option_d' => 'mabagapama',
            ],
            [
                'huruf_id' => 'H-GO-MI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'みぴぎじびき',
                'correct_answer' => 'b',
                'option_a' => 'mipigijikiki',
                'option_b' => 'mipigijibiki',
                'option_c' => 'mibigikijiki',
                'option_d' => 'mibikigipiki',
            ],
            [
                'huruf_id' => 'H-GO-MU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'むぶずぐぷづ',
                'correct_answer' => 'a',
                'option_a' => 'mubuzugupuzu',
                'option_b' => 'mubuzubuguzu',
                'option_c' => 'mubusugubuzu',
                'option_d' => 'mubuguzupuzu',
            ],
            [
                'huruf_id' => 'H-GO-ME',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'めべげでれぺ',
                'correct_answer' => 'c',
                'option_a' => 'mebegegerepe',
                'option_b' => 'mebegezerere',
                'option_c' => 'mebegedeerepe',
                'option_d' => 'mebegedezere',
            ],
            [
                'huruf_id' => 'H-GO-MO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'もぼごぽどそ',
                'correct_answer' => 'b',
                'option_a' => 'mobogopodoso',
                'option_b' => 'mobogopodoso',
                'option_c' => 'mobogodoposo',
                'option_d' => 'mobogopodoko',
            ],
            //end ma groups
            //n groups
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'んばんだんが',
                'correct_answer' => 'c',
                'option_a' => 'nbandanga',
                'option_b' => 'nbadandaga',
                'option_c' => 'nbandanga',
                'option_d' => 'nbandanga',
            ],
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'んじんぴょん',
                'correct_answer' => 'a',
                'option_a' => 'njinpyon',
                'option_b' => 'nzinpiyon',
                'option_c' => 'njinbiyon',
                'option_d' => 'nshinpyon',
            ],
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'んぐんぼんず',
                'correct_answer' => 'd',
                'option_a' => 'ngunbonzu',
                'option_b' => 'nkunbonzu',
                'option_c' => 'nganbonzu',
                'option_d' => 'ngunbonzu',
            ],
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'んぺんげんで',
                'correct_answer' => 'b',
                'option_a' => 'npenkendede',
                'option_b' => 'npenkende',
                'option_c' => 'npenkengeru',
                'option_d' => 'npenkenze',
            ],
            [
                'huruf_id' => 'H-GO-N',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'んぽんまんち',
                'correct_answer' => 'a',
                'option_a' => 'npommanchi',
                'option_b' => 'nponmanchi',
                'option_c' => 'nponmachi',
                'option_d' => 'npunmanchi',
            ],
            //end n groups
        ];

        //begimer huruf katakana
        $soalBeginnerKatakana = [
            //a groups
            [
                'huruf_id' => 'K-GO-A',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ア',
                'correct_answer' => 'b',
                'option_a' => 'e',
                'option_b' => 'a',
                'option_c' => 'o',
                'option_d' => 'i',
            ],
            [
                'huruf_id' => 'K-GO-I',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'イ',
                'correct_answer' => 'a',
                'option_a' => 'i',
                'option_b' => 'e',
                'option_c' => 'a',
                'option_d' => 'u',
            ],
            [
                'huruf_id' => 'K-GO-U',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ウ',
                'correct_answer' => 'd',
                'option_a' => 'o',
                'option_b' => 'i',
                'option_c' => 'e',
                'option_d' => 'u',
            ],
            [
                'huruf_id' => 'K-GO-E',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'エ',
                'correct_answer' => 'c',
                'option_a' => 'a',
                'option_b' => 'u',
                'option_c' => 'e',
                'option_d' => 'o',
            ],
            [
                'huruf_id' => 'K-GO-O',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'オ',
                'correct_answer' => 'b',
                'option_a' => 'u',
                'option_b' => 'o',
                'option_c' => 'a',
                'option_d' => 'e',
            ],
            //end a groups
            //ta groups
            [
                'huruf_id' => 'K-GO-TA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'タ',
                'correct_answer' => 'c',
                'option_a' => 'to',
                'option_b' => 'chi',
                'option_c' => 'ta',
                'option_d' => 'te',
            ],
            [
                'huruf_id' => 'K-GO-CHI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'チ',
                'correct_answer' => 'a',
                'option_a' => 'chi',
                'option_b' => 'shi',
                'option_c' => 'tsu',
                'option_d' => 'ta',
            ],
            [
                'huruf_id' => 'K-GO-TSU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ツ',
                'correct_answer' => 'd',
                'option_a' => 'su',
                'option_b' => 'to',
                'option_c' => 'te',
                'option_d' => 'tsu',
            ],
            [
                'huruf_id' => 'K-GO-TE',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'テ',
                'correct_answer' => 'b',
                'option_a' => 'ta',
                'option_b' => 'te',
                'option_c' => 'chi',
                'option_d' => 'tsu',
            ],
            [
                'huruf_id' => 'K-GO-TO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ト',
                'correct_answer' => 'a',
                'option_a' => 'to',
                'option_b' => 'te',
                'option_c' => 'ta',
                'option_d' => 'chi',
            ],
            //end ta groups
            //ma groups
            [
                'huruf_id' => 'K-GO-MA',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'マ',
                'correct_answer' => 'd',
                'option_a' => 'mo',
                'option_b' => 'mu',
                'option_c' => 'me',
                'option_d' => 'ma',
            ],
            [
                'huruf_id' => 'K-GO-MI',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ミ',
                'correct_answer' => 'a',
                'option_a' => 'mi',
                'option_b' => 'mu',
                'option_c' => 'ma',
                'option_d' => 'me',
            ],
            [
                'huruf_id' => 'K-GO-MU',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'ム',
                'correct_answer' => 'c',
                'option_a' => 'me',
                'option_b' => 'mo',
                'option_c' => 'mu',
                'option_d' => 'mi',
            ],
            [
                'huruf_id' => 'K-GO-ME',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'メ',
                'correct_answer' => 'b',
                'option_a' => 'mu',
                'option_b' => 'me',
                'option_c' => 'mi',
                'option_d' => 'ma',
            ],
            [
                'huruf_id' => 'K-GO-MO',
                'question' => 'Bagaimana pelafalan karakter berikut?',
                'character' => 'モ',
                'correct_answer' => 'a',
                'option_a' => 'mo',
                'option_b' => 'ma',
                'option_c' => 'mu',
                'option_d' => 'me',
            ],
            //end ma groups
            //n groups
            [
            'huruf_id' => 'K-GO-N',
            'question' => 'Bagaimana pelafalan karakter berikut?',
            'character' => 'ン',
            'correct_answer' => 'a',
            'option_a' => 'n',
            'option_b' => 'm',
            'option_c' => 'u',
            'option_d' => 'o',
            ],
        //end n groups
      
        ];
    
        foreach ($soalBeginner as $soal) {
            DB::table('soal_quis_hurufs')->insert([
                'huruf_id' => $soal['huruf_id'],
                'question' => $soal['question'],
                'jenis' => 'hiragana',
                'level' => 'beginner',
                'character' => $soal['character'],
                'correct_answer' => $soal['correct_answer'],
                'option_a' => $soal['option_a'],
                'option_b' => $soal['option_b'],
                'option_c' => $soal['option_c'],
                'option_d' => $soal['option_d'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        foreach ($soalIntermediate as $soal) {
            DB::table('soal_quis_hurufs')->insert([
                'huruf_id' => $soal['huruf_id'],
                'question' => $soal['question'],
                'jenis' => 'hiragana',
                'level' => 'intermediate',
                'character' => $soal['character'],
                'correct_answer' => $soal['correct_answer'],
                'option_a' => $soal['option_a'],
                'option_b' => $soal['option_b'],
                'option_c' => $soal['option_c'],
                'option_d' => $soal['option_d'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        foreach ($soalAdvanced as $soal) {
            DB::table('soal_quis_hurufs')->insert([
                'huruf_id' => $soal['huruf_id'],
                'question' => $soal['question'],
                'jenis' => 'hiragana',
                'level' => 'advanced',
                'character' => $soal['character'],
                'correct_answer' => $soal['correct_answer'],
                'option_a' => $soal['option_a'],
                'option_b' => $soal['option_b'],
                'option_c' => $soal['option_c'],
                'option_d' => $soal['option_d'],
                'created_at' => now(),
            ]);
        }

        foreach ($soalBeginnerKatakana as $soal) {
            DB::table('soal_quis_hurufs')->insert([
                'huruf_id' => $soal['huruf_id'],
                'question' => $soal['question'],
                'jenis' => 'katakana',
                'level' => 'beginner',
                'character' => $soal['character'],
                'correct_answer' => $soal['correct_answer'],
                'option_a' => $soal['option_a'],
                'option_b' => $soal['option_b'],
                'option_c' => $soal['option_c'],
                'option_d' => $soal['option_d'],
                'created_at' => now(),
               
            ]);
        }
    }
}
